### ISSUE TITLE
guld fee reduction

### ISSUE THREAD

**Issue by isysd** [guldcoin/Docs#3]
Guld registrations are getting expensive.

__Current Price Table__

|Category|Keys|Registration Cost|$ Cost|
|------|------|------|------|
|device|user or group as parent|0.1 guld|$7.5|
|user|one parent key|1 guld|$75|
|group|1-10 user(s) as parents|1 guld / member|$75/member|
|medium group|11-100 users as parents|100 guld|$7,500|
|large group|101-1,000 users as parents|1,000 guld|$75,000|
|enterprise group|1,001+ users as parents|10,000 guld|$750,000|

Suggest reducing fees by 90% across the board, and crediting existing users with matching rebates. Supply impact would be re-issuing 18874.8 GULD (1.8%) mostly to the `spartan` and `betatown` groups.

__New Price Table__

|Category|Keys|Registration Cost|$ Cost|
|------|------|------|------|
|device|user or group as parent|0.01 guld|$0.75|
|user|one parent key|0.1 guld|$7.5|
|group|1-10 user(s) as parents|0.1 guld / member|$7.5/member|
|medium group|11-100 users as parents|10 guld|$750|
|large group|101-1,000 users as parents|100 guld|$7,500|
|enterprise group|1,001+ users as parents|1,000 guld|$75,000|

##### individual fee recovery

```
2018/03/31 * individual registration fee rebate
    Username:Assets   0.9 x GULD
    Username:Income:guld:register:fee-rebate   -0.9 x GULD
    guld:Liabilities   -0.9 GULD
    guld:Income:register:individual:Username   0.9 GULD
```

##### group fee recovery

```
2018/03/31 * group registration fee rebate
    groupname:Assets   m * 0.9 GULD
    groupname:Income:guld:register:fee-rebate   -m * 0.9 GULD
    guld:Liabilities   -m * 0.9 GULD
    guld:Income:register:group:groupname   m * 0.9 GULD
```

These transactions will be runnable a single time and will rebate the individual or group that registered the name.

**Comment by philfog** [comment]
Would this essential function as a 1:9 split or would it reduce all total value of GULD by 90%?

**Comment by isysd** [comment]
You've got it backwards @philfog. It would make each GULD 10x as useful, i.e. able to register 10x as many names. This increases the network capacity proportionally. It is not a split at all, and only coins which were already "burned" as part of a name registration would b affected. As noted, the overall supply impact is ~1.8%.

**Comment by isysd** [comment]
Yes you missed. We're changing fees, not supply directly (only 1.8%) and not price directly (market will react).

# old

total GULD = n
current value of GULD = $75
total value = 75n

# new

total GULD = n * 1.0178
new value of GULD = $75
total value = n * 75 * 1.0178

**Comment by isysd** [comment]
This has been accomplished with an update to python-guldlib, gai and by running an update script.
